export const CONTACTS_LIST_REQUEST = "CONTACT_LIST_REQUEST";
export const CONTACTS_LIST_SUCCESS = "CONTACT_LIST_SUCCESS";
export const CONTACTS_LIST_FAIL = "CONTACT_LIST_FAIL";

export const CONTACTS_CREATE_REQUEST = "CONTACTS_CREATE_REQUEST";
export const CONTACTS_CREATE_SUCCESS = "CONTACTS_CREATE_SUCCESS";
export const CONTACTS_CREATE_FAIL = "CONTACT_CREATE_FAIL";

export const CONTACTS_UPDATE_REQUEST = "CONTACTS_UPDATE_REQUEST";
export const CONTACTS_UPDATE_SUCCESS = "CONTACTS_UPDATE_SUCCESS";
export const CONTACTS_UPDATE_FAIL = "CONTACT_UPDATE_FAIL";

export const CONTACTS_DELETE_REQUEST = "CONTACTS_DELETE_REQUEST";
export const CONTACTS_DELETE_SUCCESS = "CONTACTS_DELETE_SUCCESS";
export const CONTACTS_DELETE_FAIL = "CONTACT_DELETE_FAIL";